<?php

use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('currencies')->delete();

        \DB::table('currencies')->insert(array (
            0 =>
            array (
                'code' => 'USD',
                'created_at' => '2020-08-22 10:46:37',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 1,
                'name' => 'US Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:37',
            ),
            1 =>
            array (
                'code' => 'GBP',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 2,
                'name' => 'British Pound',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '£',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            2 =>
            array (
                'code' => 'EUR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 3,
                'name' => 'Euro',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '€',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            3 =>
            array (
                'code' => 'ZAR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 4,
                'name' => 'South African Rand',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'R',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            4 =>
            array (
                'code' => 'DKK',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 5,
                'name' => 'Danish Krone',
                'precision' => 2,
                'swap_currency_symbol' => 1,
                'symbol' => 'kr',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            5 =>
            array (
                'code' => 'ILS',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 6,
                'name' => 'Israeli Shekel',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'NIS ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            6 =>
            array (
                'code' => 'SEK',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 7,
                'name' => 'Swedish Krona',
                'precision' => 2,
                'swap_currency_symbol' => 1,
                'symbol' => 'kr',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            7 =>
            array (
                'code' => 'KES',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 8,
                'name' => 'Kenyan Shilling',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'KSh ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            8 =>
            array (
                'code' => 'KWD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 9,
                'name' => 'Kuwaiti Dinar',
                'precision' => 3,
                'swap_currency_symbol' => 0,
                'symbol' => 'KWD ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            9 =>
            array (
                'code' => 'CAD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 10,
                'name' => 'Canadian Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'C$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            10 =>
            array (
                'code' => 'PHP',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 11,
                'name' => 'Philippine Peso',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'P ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            11 =>
            array (
                'code' => 'INR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 12,
                'name' => 'Indian Rupee',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '₹',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            12 =>
            array (
                'code' => 'AUD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 13,
                'name' => 'Australian Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            13 =>
            array (
                'code' => 'SGD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 14,
                'name' => 'Singapore Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'S$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            14 =>
            array (
                'code' => 'NOK',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 15,
                'name' => 'Norske Kroner',
                'precision' => 2,
                'swap_currency_symbol' => 1,
                'symbol' => 'kr',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            15 =>
            array (
                'code' => 'NZD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 16,
                'name' => 'New Zealand Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            16 =>
            array (
                'code' => 'VND',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 17,
                'name' => 'Vietnamese Dong',
                'precision' => 0,
                'swap_currency_symbol' => 0,
                'symbol' => '₫',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            17 =>
            array (
                'code' => 'CHF',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 18,
                'name' => 'Swiss Franc',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'Fr.',
                'thousand_separator' => '\'',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            18 =>
            array (
                'code' => 'GTQ',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 19,
                'name' => 'Guatemalan Quetzal',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'Q',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            19 =>
            array (
                'code' => 'MYR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 20,
                'name' => 'Malaysian Ringgit',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'RM',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            20 =>
            array (
                'code' => 'BRL',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 21,
                'name' => 'Brazilian Real',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'R$',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            21 =>
            array (
                'code' => 'THB',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 22,
                'name' => 'Thai Baht',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '฿',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            22 =>
            array (
                'code' => 'NGN',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 23,
                'name' => 'Nigerian Naira',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '₦',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            23 =>
            array (
                'code' => 'ARS',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 24,
                'name' => 'Argentine Peso',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            24 =>
            array (
                'code' => 'BDT',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 25,
                'name' => 'Bangladeshi Taka',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'Tk',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            25 =>
            array (
                'code' => 'AED',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 26,
                'name' => 'United Arab Emirates Dirham',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'DH ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            26 =>
            array (
                'code' => 'HKD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 27,
                'name' => 'Hong Kong Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'HK$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            27 =>
            array (
                'code' => 'IDR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 28,
                'name' => 'Indonesian Rupiah',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'Rp',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            28 =>
            array (
                'code' => 'MXN',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 29,
                'name' => 'Mexican Peso',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            29 =>
            array (
                'code' => 'EGP',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 30,
                'name' => 'Egyptian Pound',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'E£',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            30 =>
            array (
                'code' => 'COP',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 31,
                'name' => 'Colombian Peso',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            31 =>
            array (
                'code' => 'XOF',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 32,
                'name' => 'West African Franc',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'CFA ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            32 =>
            array (
                'code' => 'CNY',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 33,
                'name' => 'Chinese Renminbi',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'RMB ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            33 =>
            array (
                'code' => 'RWF',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 34,
                'name' => 'Rwandan Franc',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'RF ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            34 =>
            array (
                'code' => 'TZS',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 35,
                'name' => 'Tanzanian Shilling',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'TSh ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            35 =>
            array (
                'code' => 'ANG',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 36,
                'name' => 'Netherlands Antillean Guilder',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'NAƒ',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            36 =>
            array (
                'code' => 'TTD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 37,
                'name' => 'Trinidad and Tobago Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'TT$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            37 =>
            array (
                'code' => 'XCD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 38,
                'name' => 'East Caribbean Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'EC$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            38 =>
            array (
                'code' => 'GHS',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 39,
                'name' => 'Ghanaian Cedi',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '‎GH₵',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            39 =>
            array (
                'code' => 'BGN',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 40,
                'name' => 'Bulgarian Lev',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'Лв.',
                'thousand_separator' => ' ',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            40 =>
            array (
                'code' => 'AWG',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 41,
                'name' => 'Aruban Florin',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'Afl. ',
                'thousand_separator' => ' ',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            41 =>
            array (
                'code' => 'TRY',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 42,
                'name' => 'Turkish Lira',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'TL ',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            42 =>
            array (
                'code' => 'RON',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 43,
                'name' => 'Romanian New Leu',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'RON',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            43 =>
            array (
                'code' => 'HRK',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 44,
                'name' => 'Croatian Kuna',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'kn',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            44 =>
            array (
                'code' => 'SAR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 45,
                'name' => 'Saudi Riyal',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '‎SِAR',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            45 =>
            array (
                'code' => 'JPY',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 46,
                'name' => 'Japanese Yen',
                'precision' => 0,
                'swap_currency_symbol' => 0,
                'symbol' => '¥',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            46 =>
            array (
                'code' => 'MVR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 47,
                'name' => 'Maldivian Rufiyaa',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'Rf',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            47 =>
            array (
                'code' => 'CRC',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 48,
                'name' => 'Costa Rican Colón',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '₡',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            48 =>
            array (
                'code' => 'PKR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 49,
                'name' => 'Pakistani Rupee',
                'precision' => 0,
                'swap_currency_symbol' => 0,
                'symbol' => 'Rs ',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            49 =>
            array (
                'code' => 'PLN',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 50,
                'name' => 'Polish Zloty',
                'precision' => 2,
                'swap_currency_symbol' => 1,
                'symbol' => 'zł',
                'thousand_separator' => ' ',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            50 =>
            array (
                'code' => 'LKR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 51,
                'name' => 'Sri Lankan Rupee',
                'precision' => 2,
                'swap_currency_symbol' => 1,
                'symbol' => 'LKR',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            51 =>
            array (
                'code' => 'CZK',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 52,
                'name' => 'Czech Koruna',
                'precision' => 2,
                'swap_currency_symbol' => 1,
                'symbol' => 'Kč',
                'thousand_separator' => ' ',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            52 =>
            array (
                'code' => 'UYU',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 53,
                'name' => 'Uruguayan Peso',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            53 =>
            array (
                'code' => 'NAD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 54,
                'name' => 'Namibian Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            54 =>
            array (
                'code' => 'TND',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 55,
                'name' => 'Tunisian Dinar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '‎د.ت',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            55 =>
            array (
                'code' => 'RUB',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 56,
                'name' => 'Russian Ruble',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '₽',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            56 =>
            array (
                'code' => 'MZN',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 57,
                'name' => 'Mozambican Metical',
                'precision' => 2,
                'swap_currency_symbol' => 1,
                'symbol' => 'MT',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            57 =>
            array (
                'code' => 'OMR',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 58,
                'name' => 'Omani Rial',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'ر.ع.',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            58 =>
            array (
                'code' => 'UAH',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 59,
                'name' => 'Ukrainian Hryvnia',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => '₴',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            59 =>
            array (
                'code' => 'MOP',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 60,
                'name' => 'Macanese Pataca',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'MOP$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            60 =>
            array (
                'code' => 'TWD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 61,
                'name' => 'Taiwan New Dollar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'NT$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            61 =>
            array (
                'code' => 'DOP',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => '.',
                'deleted_at' => NULL,
                'id' => 62,
                'name' => 'Dominican Peso',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'RD$',
                'thousand_separator' => ',',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            62 =>
            array (
                'code' => 'CLP',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 63,
                'name' => 'Chilean Peso',
                'precision' => 0,
                'swap_currency_symbol' => 0,
                'symbol' => '$',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            63 =>
            array (
                'code' => 'RSD',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 64,
                'name' => 'Serbian Dinar',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'RSD',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
            64 =>
            array (
                'code' => 'KGS',
                'created_at' => '2020-08-22 10:46:38',
                'decimal_separator' => ',',
                'deleted_at' => NULL,
                'id' => 65,
                'name' => 'Kyrgyzstani som',
                'precision' => 2,
                'swap_currency_symbol' => 0,
                'symbol' => 'С̲ ',
                'thousand_separator' => '.',
                'updated_at' => '2020-08-22 10:46:38',
            ),
        ));


    }
}
