<?php

use Illuminate\Database\Seeder;

class ProductCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_categories')->delete();
        
        \DB::table('product_categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Autos, Motos y Otros',
                'code' => 'autos-motos-y-otros',
                'slug' => 'autos-motos-y-otros',
                'position' => 1,
                'image' => '/storage/categories/8f3009183f1520aaf4090e3fc7205b37.jpg',
                'icon' => 'fas fa-car',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:12:39',
                'updated_at' => '2020-10-21 18:17:18',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Cámaras y Accesorios',
                'code' => 'cmaras-y-accesorios',
                'slug' => 'cmaras-y-accesorios',
                'position' => 2,
                'image' => '/storage/categories/1dc4472afbe1bb1db133733d53fe7ddb.jpg',
                'icon' => 'fas fa-camera-retro',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:13:54',
                'updated_at' => '2020-10-21 18:21:32',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Consolas y Videojuegos',
                'code' => 'consolas-y-videojuegos',
                'slug' => 'consolas-y-videojuegos',
                'position' => 3,
                'image' => '/storage/categories/42714683455311240d39a23ec39671f7.jpg',
                'icon' => 'fas fa-gamepad',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:14:20',
                'updated_at' => '2020-10-21 18:21:54',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Electrodomésticos',
                'code' => 'electrodomsticos',
                'slug' => 'electrodomsticos',
                'position' => 4,
                'image' => '/storage/categories/de323c0f3f011505960020a8fd61c560.jpg',
                'icon' => 'far fa-hdd',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:15:07',
                'updated_at' => '2020-10-21 18:23:43',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Hogar y Muebles',
                'code' => 'hogar-y-muebles',
                'slug' => 'hogar-y-muebles',
                'position' => 5,
                'image' => '/storage/categories/035b0c046a5d9fd08d2fe69404ac68df.jpg',
                'icon' => 'fas fa-couch',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:15:31',
                'updated_at' => '2020-10-21 18:23:53',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Vestuario y Calzado',
                'code' => 'vestuario-y-calzado',
                'slug' => 'vestuario-y-calzado',
                'position' => 6,
                'image' => '/storage/categories/dcfe8b1d14105beee6a73b07307eb498.jpg',
                'icon' => 'fas fa-tshirt',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:15:51',
                'updated_at' => '2020-10-21 18:26:03',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Belleza y Cuidado Personal',
                'code' => 'belleza-y-cuidado-personal',
                'slug' => 'belleza-y-cuidado-personal',
                'position' => 7,
                'image' => '/storage/categories/85bbea7b080aed36fbb3259c26a19d64.jpg',
                'icon' => 'fas fa-cut',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:16:10',
                'updated_at' => '2020-10-21 18:21:06',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Celulares y Telefonía',
                'code' => 'celulares-y-telefona',
                'slug' => 'celulares-y-telefona',
                'position' => 8,
                'image' => '/storage/categories/a33371170085ef8cd62bf4141e76e975.jpg',
                'icon' => 'fas fa-phone',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:16:24',
                'updated_at' => '2020-10-21 18:21:22',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Computación',
                'code' => 'computacion',
                'slug' => 'computacin',
                'position' => 9,
                'image' => '/storage/categories/d7663cf9962aac575d8a687023804eaa.jpg',
                'icon' => 'fas fa-desktop',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:16:49',
                'updated_at' => '2020-10-21 18:21:47',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Electrónica, Audio y Video',
                'code' => 'electrnica-audio-y-video',
                'slug' => 'electrnica-audio-y-video',
                'position' => 10,
                'image' => '/storage/categories/346534cc11dc6927fc052374da32b2fe.jpg',
                'icon' => 'fab fa-soundcloud',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:17:07',
                'updated_at' => '2020-10-21 18:22:32',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Accesorios para Vehículos',
                'code' => 'accesorios-para-vehculos',
                'slug' => 'accesorios-para-vehculos',
                'position' => 11,
                'image' => '/storage/categories/6327ef49acc36ac245bfb8a6f204c003.jpg',
                'icon' => 'fas fa-car-side',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:17:44',
                'updated_at' => '2020-10-21 18:15:53',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Deporte y Fitness',
                'code' => 'deporte-y-fitness',
                'slug' => 'deporte-y-fitness',
                'position' => 12,
                'image' => '/storage/categories/d4a09806e1a430afc5ab132d2c03e00d.jpg',
                'icon' => 'fas fa-basketball-ball',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:18:16',
                'updated_at' => '2020-10-21 18:22:09',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Juegos y Juguetes',
                'code' => 'juegos-y-juguetes',
                'slug' => 'juegos-y-juguetes',
                'position' => 13,
                'image' => '/storage/categories/3b9fcbf2fb4c5f992aaeca35b22090e6.jpg',
                'icon' => 'fas fa-tachometer-alt',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:18:34',
                'updated_at' => '2020-10-21 18:25:22',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Bebés',
                'code' => 'bebes',
                'slug' => 'bebes',
                'position' => 14,
                'image' => '/storage/categories/64eebb9efca72fb052e028599d9891f2.jpg',
                'icon' => 'fab fa-reddit-square',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:18:58',
                'updated_at' => '2020-10-21 18:19:51',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Alimentos y bebidas',
                'code' => 'alimentos-y-bebidas',
                'slug' => 'alimentos-y-bebidas',
                'position' => 15,
                'image' => '/storage/categories/7952921cd02f8ff01c6018e02219ba53.jpg',
                'icon' => 'fas fa-bone',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:19:16',
                'updated_at' => '2020-10-21 18:17:04',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Accesorios de moda',
                'code' => 'accesorios-de-moda',
                'slug' => 'accesorios-de-moda',
                'position' => 16,
                'image' => '/storage/categories/6fa7c5c380416138e4c3c594a193b11a.jpg',
                'icon' => 'fas fa-tshirt',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:19:30',
                'updated_at' => '2020-10-21 18:14:57',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Instituciones benéficas',
                'code' => 'instituciones-benficas',
                'slug' => 'instituciones-benficas',
                'position' => 17,
                'image' => '/storage/categories/dd7869fb30c2005bef3e491625e0a9ac.jpg',
                'icon' => 'fas fa-donate',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:19:49',
                'updated_at' => '2020-10-21 18:24:02',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Servicios',
                'code' => 'servicios',
                'slug' => 'servicios',
                'position' => 18,
                'image' => '/storage/categories/e3d2e170825f0658624916fc15510245.jpg',
                'icon' => 'far fa-user-circle',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:20:41',
                'updated_at' => '2020-10-21 18:25:53',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Viajes y Turismo',
                'code' => 'viajes-y-turismo',
                'slug' => 'viajes-y-turismo',
                'position' => 19,
                'image' => '/storage/categories/edf566d18d73724a20529d331f1c7368.jpg',
                'icon' => 'fas fa-train',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:20:58',
                'updated_at' => '2020-10-21 18:26:17',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Mascotas',
                'code' => 'mascota',
                'slug' => 'mascota',
                'position' => 20,
                'image' => '/storage/categories/576860dd27f459292d0e7aca42748bdb.jpg',
                'icon' => 'fas fa-bone',
                'display_mode' => 'products_and_description',
                'parent_id' => NULL,
                'status' => 1,
                'company_id' => 1,
                'created_at' => '2020-10-14 17:21:14',
                'updated_at' => '2020-10-21 18:25:36',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}